version: "3.8"

services:
  idserv:
    image: idserv4
    container_name: idserv4
    build:
      context: ./IdentityServer/IdentityServer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:5000/
      - IS_DOCKER=true
    ports:
      - 5000:5000
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 

  myapp-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/client/src
    env_file:
      - ./frontend/.env

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - 3001:3001
    volumes:
      - ./server:/app/server
      - ./server/node_modules:/app/server/node_modules
    depends_on: 
      - mysqldb

  mysqldb:
    container_name: webapp-project-db
    image: mysql:latest
    environment: 
      - MYSQL_DATABASE=webapp-project
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
volumes:
  mysql-vol: