export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",

  ADD_CART: "ADD_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART"
};
